theme: jekyll-theme-minimal
title: Ethan's homepage
description: Bookmark this to keep an eye on my project updates!
domain: ethan-wu.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://ethan-wu.github.io  # the base hostname and protocol for your site, e.g. http://example.com
